### PR TITLE
Newsweek's main page recreation using bootstrap.

### PR DESCRIPTION
**Pull request by RodolfoRodriguezMata**
This project recreates Newsweek's layout using bootstrap and how it reacts whenever the width of the view-port is affected. It has three possible set-ups, one above 1024px for computer screens and above, another one from 1023px down to 768px for handheld screens that allow for several column's worth of content and finally one that goes down from 767px for mobile screens that allow a single stream-lined column of content.

### CODE REVIEW

**Comment by shshamim63** [comment]
## Status :recycle: [!! Required Changes !!] :recycle: 
___
Hi @RodolfoRodriguezMata :wave.
You have gathered all the items needed to decorate the page, no lint errors, no HTML markup validation errors :clap: . But Some of items need to be placed correctly on the page. 
___
##### Please follow the instructions below to declare this project as complete.
___
### :satellite: [Mandatory Changes] :satellite: 
___
#### :desktop_computer: Large Screen
1. Navbar Section -> The logo is really small compared to actual webpage. And it should render at the middle. My screen resolution is (1920 x 1200). But as this is a Bootstrap project and also responsive so should cover all the screen resolution.
image You can chekc your project on this [link](https://responsivedesignchecker.com/) to get the overall idea about the rendering.
2. The image of the both feature stories and top stories picture are not possessing the full of their dedicated with as the actual one. I can see image as above :point_up: .
___
#### :computer: : Medium Screen
1. The nabvar elements are not rendering properly. And it should consist a hamburger icon. Like the original one. 
image
___
#### :iphone: : : Small Screen
1. The page contains white space to its right. Is because of the footer. If you inspect the page you will get the cause of it. Also the navbar of the small screen view is broken.
image
___
#### Please fix the above mentioned issue and send a review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](__Shakhawat Hossain__)

**Comment by shshamim63** [comment]
## Status :ballot_box_with_check: [!! Required Changes !!] :ballot_box_with_check: 
___
Hi @RodolfoRodriguezMata  :wave: ,
Great job :clap: , you have fixed all the issues raised previously. But it generates some new issue now. And these issue are actually destroying the look of this project. You have to dive in a little bit dipper to cover all the issues. I believe you will do it. (Please inspect your project with the browsers devtool, so that you can compare your project flow with the actual one.)
___
#### Please follow the instructions below to complete this project. 
___
### :sparkle:  [Mandatory Changes] :sparkle: 
___
1. You were suppose to check HTML markup with this validator [https://validator.w3.org/#validate_by_upload](https://validator.w3.org/#validate_by_upload). I can see an error on it. So please fix that error. 

---
##### :desktop_computer: Large Screen View

---
1. The `FEATURED STORIES` is not aligned properly with its neighbor element. 
image
2. The navbar items are broken. If you check the original one you will see the a major difference.
image
3. Actual page contains some space to its right and to its left. But your one contains the full width.
image

---
##### :computer:  Medium Screen View
___
1. The `Top Stories section is hidden under the navbar. Please fix that too.
image

---
##### :iphone: :  Small Screen View
___
1. The social icons on the footer is also broken. You have to take care of that part too.
image
___
#### Please fix the above mentioned issue and send another request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](__Shakhawat Hossain__)

**Comment by shshamim63** [comment]
## :ballot_box_with_check: [!! Changes Required !!] :ballot_box_with_check: 
___
Hi @RodolfoRodriguezMata :wave: 
You have covered most of the changes asked in the previous comments. But still there some major issues that are breaking the flow of this project. So if you inspect the page using browser devtool you will see the same issues.
___
### Please follow the instructions below to complete this project.
___
### :spades: [Mandatory Changes] :spades: 
___
**:desktop_computer:  Large Screen**

1. More stories section is collapsing with the sponsored section.
image
2. Still the navbar is broken.
image
3. Footer is also broken.
image

---
**:computer: Medium Screen**

1. Footer is Broken.
image

---
**:iphone: Small Screen** 

1. SPONSORED Section is overflowing the window size.
image
___
### Please fix all the changes and inspect it on different sizes and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

**Review by mosesogwo — CHANGES_REQUESTED** [review]
### HI @RodolfoRodriguezMata, :clap: great job so far but we are not good to :airplane: yet.
- You haven't fixed the overlapping in the **More stories section** pointed out in the last review
- You have a huge empty space under the **In The Magazine section**. It should be filled up.
- You have horizontally overflowing items in several sections on small screen sizes.
- **Besides the issues I have pointed out, kindly pick each section of the page and ensure that it displays correctly on _large_, _medium_ and _small_ screen sizes (as it is aligned on the original page) before submitting for another code review.**

### Please take time to find out how to align these items properly. More grease to your 💪

**Comment by kobiyoyo** [comment]
### Pull Request under review, by Adama Chubiyojo Desmond (TSE)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @RodolfoRodriguezMata   
#### Great Job so far, but there is one thing required. 

### Page structure
- [ ] Please fix the hamburger menu .




### Make changes and submit another code review request.
*Happy coding*

**Comment by izaiasneto4** [comment]
### Hi @RodolfoRodriguezMata. Great job implementing those changes, we're almost there 👍. There's just one thing left for us to finish it ⬇️ 

- [ ] Let's fix the errors given by the [HTML validator](https://validator.w3.org/#validate_by_upload)

Please, when finished with these changes submit your project again for a new review 🙏

**Comment by RodolfoRodriguezMata** [comment]
I'm sorry but I have run the html and the raw.githack link through this validator: https://validator.w3.org and it shows no issues found. Could you please orient me as to what is being shown?

**Review by kobiyoyo — APPROVED** [review]
# Project Approved :thumbsup:
## Hello @RodolfoRodriguezMata  ,  You have done a great job with this project. :clap:

**Comment by RodolfoRodriguezMata** [comment]
Thank you very much for your help!

**Pull request merged**
